/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.BillController;
import controller.ExportController;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.IOException;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.NumberFormat;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import model.DataAccessHelper;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author tnd
 */
public class FBill extends MyFrame {
    BillController Controller=new BillController();
    /**
     * Creates new form FBill
     */
    private static FBill instance=null;
    private int BillID;
    public static FBill getInstance(){
        if(instance==null)
            instance=new FBill();
        return instance;
    }
    private FBill() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cbCustomer = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txfDate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txfSearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProduct = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        spCount = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableBill = new javax.swing.JTable();
        btnExit = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txfValue = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txfMoneyReceive = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txfChange = new javax.swing.JTextField();
        jPrintBill = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lập hóa đơn");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(33, 115, 70));
        jLabel1.setText("Lập hóa đơn");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(422, 422, 422)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(33, 115, 70));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nhập thông tin hóa đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Khách hàng");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ngày hóa đơn");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Sản phẩm");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1.setText("Tìm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tableProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Giá bán"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableProduct);

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRemove.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRemove.setText("Xóa");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpdate.setText("Sửa");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Số lượng");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spCount, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnUpdate)
                                .addGap(37, 37, 37)
                                .addComponent(btnRemove)
                                .addGap(31, 31, 31)
                                .addComponent(btnAdd))))
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(txfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1))
                        .addComponent(jLabel6)
                        .addComponent(cbCustomer, 0, 333, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addComponent(txfDate)))
                .addGap(58, 58, 58))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(txfDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUpdate)
                            .addComponent(btnRemove)
                            .addComponent(btnAdd))
                        .addContainerGap())))
        );

        jPanel3.setBackground(new java.awt.Color(33, 115, 70));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nhập thông tin hóa đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        tableBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Giá bán", "Tổng tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableBill);

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExit.setText("Thoát");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSave.setText("Lưu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnNew.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNew.setText("Tạo mới");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tổng tiền thanh toán");

        txfValue.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Số tiền nhận");

        txfMoneyReceive.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                FBill.this.inputMethodTextChanged(evt);
            }
        });
        txfMoneyReceive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfMoneyReceiveActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Còn lại");

        txfChange.setEnabled(false);

        jPrintBill.setText("In hoá đơn");
        jPrintBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPrintBillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(35, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txfMoneyReceive, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                    .addComponent(txfChange))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 114, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPrintBill)
                                .addGap(18, 18, 18)
                                .addComponent(btnNew)
                                .addGap(33, 33, 33)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txfValue, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnSave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnExit)
                                .addGap(18, 18, 18))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txfValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txfMoneyReceive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txfChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNew)
                    .addComponent(btnSave)
                    .addComponent(btnExit)
                    .addComponent(jPrintBill))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        FManagement.getInstance().removeFormInQueue(this);
    }//GEN-LAST:event_btnExitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Controller.searchBook(txfSearch.getText(),tableProduct);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try{
            String name=tableProduct.getModel().getValueAt(tableProduct.getSelectedRow(),2).toString();
            String supplierName=tableProduct.getModel().getValueAt(tableProduct.getSelectedRow(),3).toString();
            String id=tableProduct.getModel().getValueAt(tableProduct.getSelectedRow(),1).toString();
            int amount=Integer.parseInt((tableProduct.getModel().getValueAt(tableProduct.getSelectedRow(),4).toString()));
            int count= (int)spCount.getValue();
            
            if(count>0)
            {
            if( count<=amount )
                    {
                        
            float price=Float.parseFloat(tableProduct.getModel().getValueAt(tableProduct.getSelectedRow(),5).toString());
            float total=count*price;
            if(checkContain()==-1 )
            {
                Object[] row=new Object[]{
                tableBill.getRowCount()+1,
                id,
                name,
                supplierName,
                count,
                price,
                total
                };
                DefaultTableModel model = (DefaultTableModel) tableBill.getModel();
                model.addRow(row);
            }
            else 
               
            {
                int rowIndex=checkContain();
                int countTable=Integer.parseInt(tableBill.getModel().getValueAt(rowIndex, 4).toString())+(int)spCount.getValue();
                
              
                if(countTable<=amount )
                {
                float priceTable=Float.parseFloat(tableProduct.getModel().getValueAt(tableProduct.getSelectedRow(),5).toString());
                float totalTable=countTable*priceTable;
                tableBill.getModel().setValueAt(countTable, rowIndex, 4);
                tableBill.getModel().setValueAt(priceTable, rowIndex, 5);
                tableBill.getModel().setValueAt(totalTable, rowIndex, 6);
                }
                else
                {
                JOptionPane.showConfirmDialog(FBill.getInstance(), "Số lượng nhập vượt quá số lượng hàng còn !","Thông báo", JOptionPane.OK_OPTION);
                }
                
            }

            float value=0;
            for(int i=0;i<tableBill.getRowCount();i++)
                value+=Float.parseFloat(tableBill.getModel().getValueAt(i, 6).toString());
            txfValue.setText(String.valueOf(value));
            
            float moneyReceive=Float.parseFloat(txfMoneyReceive.getText());
            txfChange.setText(String.valueOf(Float.parseFloat(txfValue.getText())-moneyReceive));
         }
             else {
                
                JOptionPane.showConfirmDialog(FBill.getInstance(), "Số lượng nhập vượt quá số lượng hàng còn !","Thông báo", JOptionPane.OK_OPTION);
                }
            }
            else
            { 
                JOptionPane.showConfirmDialog(FBill.getInstance(), "Số lượng nhập không được nhỏ hơn 0 !","Thông báo", JOptionPane.OK_OPTION);
            
            }
            
        }
        catch(Exception e){}
        
        
       
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        try{
            ((DefaultTableModel)tableBill.getModel()).removeRow(tableBill.getSelectedRow());
            for(int i=0;i<tableBill.getRowCount();i++)
                tableBill.getModel().setValueAt(i+1,i,0);
        }catch(Exception e){           
        }
        
        float value=0;
        for(int i=0;i<tableBill.getRowCount();i++)
            value+=Float.parseFloat(tableBill.getModel().getValueAt(i, 5).toString());
        txfValue.setText(String.valueOf(value));
        
        float moneyReceive=Float.parseFloat(txfMoneyReceive.getText());
        txfChange.setText(String.valueOf(Float.parseFloat(txfValue.getText())-moneyReceive)); 
  
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try{
            int rowIndex=tableBill.getSelectedRow();
            int countTable=Integer.parseInt(tableBill.getModel().getValueAt(rowIndex, 3).toString());
            float priceTable=Float.parseFloat(tableBill.getModel().getValueAt(rowIndex, 4).toString());
            float totalTable=countTable*priceTable;
            tableBill.getModel().setValueAt(totalTable, rowIndex, 5);


            float value=0;
            for(int i=0;i<tableBill.getRowCount();i++)
                value+=Float.parseFloat(tableBill.getModel().getValueAt(i, 5).toString());
            txfValue.setText(String.valueOf(value));
            
            float moneyReceive=Float.parseFloat(txfMoneyReceive.getText());
            txfChange.setText(String.valueOf(Float.parseFloat(txfValue.getText())-moneyReceive));
            
        }catch(Exception e){}
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txfMoneyReceiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfMoneyReceiveActionPerformed
       
//         Locale lc = new Locale("nv","VN");
//         BigDecimal c1=new BigDecimal(txfMoneyReceive.getText());
//           
//           txfMoneyReceive.setText(NumberFormat.getCurrencyInstance(lc).format(c1));
//        try{
//            float moneyReceive=Float.parseFloat(txfMoneyReceive.getText());
//            txfChange.setText(String.valueOf(Float.parseFloat(txfValue.getText())-moneyReceive));
//        }catch(NumberFormatException e){
//            JOptionPane.showConfirmDialog(FBill.getInstance(), "Nhập dữ liệu không đúng định dạng !","Thông báo", JOptionPane.OK_OPTION);
//        }
    }//GEN-LAST:event_txfMoneyReceiveActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        releaseAction();
        reload();
        addAction();
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        int rowCount=tableBill.getRowCount();
        String[][]data=new String[rowCount][5];
        for(int i=0;i<rowCount;i++)
        {
            data[i][0]=tableBill.getModel().getValueAt(i, 1).toString();
            data[i][1]=tableBill.getModel().getValueAt(i, 3).toString();
            data[i][2]=tableBill.getModel().getValueAt(i, 4).toString();
            data[i][3]=tableBill.getModel().getValueAt(i, 5).toString();
            data[i][4]=tableBill.getModel().getValueAt(i, 6).toString();
        }
        String date=txfDate.getText();
        String value=txfValue.getText();
        String moneyReceive=txfMoneyReceive.getText();
         try{
              
             txfChange.setText(String.valueOf(Float.parseFloat(moneyReceive)-Float.parseFloat(value)));
        }catch(NumberFormatException e){
            JOptionPane.showConfirmDialog(FBill.getInstance(), "Nhập dữ liệu không đúng định dạng !","Thông báo", JOptionPane.OK_OPTION);
        }
       
        String moneyChange=txfChange.getText();
        String customerID=cbCustomer.getSelectedItem().toString().split(":")[1];
        
        
        try {
            if(Controller.AddBill(data,date,value,moneyReceive,moneyChange,customerID))
            {
                JOptionPane.showConfirmDialog(FBill.getInstance(), "Lưu hóa đơn thành công !","Thông báo", JOptionPane.OK_OPTION);
                
                 
                String SQL="Select max(Numbill)as ID from Bill";
                DataAccessHelper.getInstance().getConnect();
                Statement statement =DataAccessHelper.getInstance().conn.createStatement();
                ResultSet rs=statement.executeQuery(SQL);
                 while(rs.next())
                 {
                BillID=Integer.parseInt(rs.getString("ID"));
                 }
                System.out.print("billlll"+BillID);
                loadProduct();
                DataAccessHelper.getInstance().getClose();
            }
            else
            {
                JOptionPane.showConfirmDialog(FBill.getInstance(), "Lưu hóa đơn thất bại !","Thông báo", JOptionPane.OK_OPTION);
                
            }
        } catch (ParseException ex) {
            Logger.getLogger(FBill.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FBill.class.getName()).log(Level.SEVERE, "Loi", ex);
        }
        
        
        //export xls
        try{
            ExportController exporter = new ExportController();
            exporter.ExportTable(tableBill, new File(System.getProperty("user.dir")+"//bill.xls"));
        }
        catch(IOException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_inputMethodTextChanged
        
        
        
//         Locale lc = new Locale("nv","VN");
//         BigDecimal c1=new BigDecimal(txfMoneyReceive.getText());
//           
//         txfMoneyReceive.setText(NumberFormat.getCurrencyInstance(lc).format(c1));

// TODO add your handling code here:
    }//GEN-LAST:event_inputMethodTextChanged

    private void jPrintBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPrintBillActionPerformed
          Connection conn = null;
        try {
            
            DataAccessHelper.getInstance().getConnect();
            conn = DataAccessHelper.getInstance().conn;
            Map<String,Object> parameters = new HashMap<String,Object>();
            parameters.put("p_order_id", BillID);
            
            JasperReport jreport = JasperCompileManager.compileReport("D:\\WORK\\DOAN\\HK2\\JAVA\\StoreManagement\\StoreManagement\\StoreManagement\\src\\view\\order.jrxml");
            JasperPrint jprint = JasperFillManager.fillReport(jreport, parameters, conn);
            JasperViewer.viewReport(jprint,false );

        } catch (JRException e) {
        }catch(SQLException exq){
            
        }                // TODO add your handling code here:
    }//GEN-LAST:event_jPrintBillActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            FBill.getInstance().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbCustomer;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jPrintBill;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner spCount;
    private javax.swing.JTable tableBill;
    private javax.swing.JTable tableProduct;
    private javax.swing.JTextField txfChange;
    private javax.swing.JTextField txfDate;
    private javax.swing.JTextField txfMoneyReceive;
    private javax.swing.JTextField txfSearch;
    private javax.swing.JTextField txfValue;
    // End of variables declaration//GEN-END:variables

    @Override
    public void reload() {
        loadCustomer();
        loadDate();
        loadProduct();
        
        txfValue.setText("0");
        txfMoneyReceive.setText("0");
        txfChange.setText("0");
        spCount.setValue(0);
        txfSearch.setText("");
        
        tableBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã sản phẩm", "Tên sản phẩm", "Nhà cung  cấp","Số lượng", "Giá bán", "Tổng tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class,java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableBill);
    }

    private void loadCustomer() {
        Controller.loadCustomer(cbCustomer);
        cbCustomer.setSelectedIndex(-1);
    }
        private void loadDate() {
        SimpleDateFormat df=new SimpleDateFormat("dd/MM/yyyy");
        Date date=new Date();
        date.getTime();
        txfDate.setText(df.format(date));
    }

    
    private int checkContain()
    {
        String id=tableProduct.getModel().getValueAt(tableProduct.getSelectedRow(),1).toString();
        String supplierid=tableProduct.getModel().getValueAt(tableProduct.getSelectedRow(),3).toString();
        for(int i=0;i<tableBill.getRowCount();i++)
        {
            if(tableBill.getModel().getValueAt(i, 1).toString().equals(id) && tableBill.getModel().getValueAt(i, 3).toString().equals(supplierid) )
                return i;
        }
        return -1;
    }

    private void loadProduct() {
        Controller.loadProduct(tableProduct);
    }

    @Override
    public void releaseAction() {
        cbCustomer.removeActionListener(cbCustomer.getActionListeners()[0]);
    }

    @Override
    public void update() {
        loadCustomer();
    }

    @Override
    public void addAction() {
        cbCustomer.addActionListener ((ActionEvent e) -> {
            if(cbCustomer.getSelectedItem().toString().equals("Thêm..."))
            {
                FManagement.getInstance().addFormToQueue(FCustomer.getInstance());
            }
        });
    }
}
