/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import controller.ReportInventoryController;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import model.DataAccessHelper;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author tnd
 */
public class FReportInventory extends MyFrame {
   
   ReportInventoryController reportController=new ReportInventoryController();
   private String product;
   private String productCategory;
   private String supplier;
   private int typeReport;
   private Date  toDate;
   private Date fromDate;
    /**
     * Creates new form FReportInventory
     */
    private static FReportInventory instance=null;
    public static FReportInventory getInstance(){
        if(instance==null)
            instance=new FReportInventory();
        return instance;
    }
    private FReportInventory() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbproductAll = new javax.swing.JComboBox<>();
        cbproductCategory = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbSupplierAll = new javax.swing.JComboBox<>();
        cbtypeReport = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        datapicker1 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        datapicker2 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(33, 115, 70));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nhập thông tin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sản Phẩm:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Loại Sản Phẩm:");

        cbproductAll.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbproductAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbproductAllActionPerformed(evt);
            }
        });

        cbproductCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nhà cung cấp:");

        cbSupplierAll.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbtypeReport.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Theo từng tháng :0", "Theo năm :1", " " }));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Loại báo cáo:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Từ: ");

        datapicker1.setMinimumSize(new java.awt.Dimension(24, 18));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Đến: ");

        jButton1.setText("Xuất báo cáo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Thoát");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbproductCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datapicker1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jButton1)
                        .addGap(35, 35, 35)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel2))
                    .addGap(13, 13, 13)
                    .addComponent(cbproductAll, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbSupplierAll, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbtypeReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(42, 42, 42))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(datapicker2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(33, 33, 33)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(cbproductCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(datapicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(cbSupplierAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)
                                .addComponent(cbproductAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(22, 22, 22)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel7)
                                .addComponent(cbtypeReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(30, 30, 30)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(datapicker2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)))
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addContainerGap(91, Short.MAX_VALUE)))
        );

        jPanel3.setBackground(new java.awt.Color(33, 115, 70));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Báo cáo tồn kho");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jLabel1)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbproductAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbproductAllActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_cbproductAllActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

         String datePattern = "dd/MM/yyyy";
        
         SimpleDateFormat dateFormatter = new SimpleDateFormat(datePattern);
         
         
        product=cbproductAll.getSelectedItem().toString().split(":")[1];
        productCategory=cbproductCategory.getSelectedItem().toString().split(":")[1];
        supplier=cbSupplierAll.getSelectedItem().toString().split(":")[1];
        
        typeReport=Integer.parseInt(cbtypeReport.getSelectedItem().toString().split(":")[1]);

        toDate = (Date) datapicker1.getDate();
        fromDate=(Date)  datapicker2.getDate();
        
        Calendar cal = Calendar.getInstance();
        cal.setTime(toDate);
        int year1 = cal.get(Calendar.YEAR);
        cal.setTime(fromDate);
        int year2 = cal.get(Calendar.YEAR);
        
        
        String date1=dateFormatter.format(toDate);
        String date2=dateFormatter.format(fromDate);
        
        
        if(typeReport==0)
        {
            if(year1==year2)
        {
           PrintReport( product,productCategory,supplier,date1,date2);
        }
            else
            {
                
            PrintReport2( product,productCategory,supplier,date1,date2);
            }
        }
        else
        {
           PrintReportToYear(product,productCategory,supplier,date1,date2);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public void PrintReport(String productID, String productTypeID, String supplierNameID,String date1,String date2)
    {
    
        Connection conn = null;
        try {

            DataAccessHelper.getInstance().getConnect();
            conn = DataAccessHelper.getInstance().conn;
            Map<String,Object> parameters = new HashMap<String,Object>();
            parameters.put("p_id", Integer.parseInt(productID));
            parameters.put("productCate_id", Integer.parseInt(productTypeID));
            parameters.put("supplier_id", Integer.parseInt(supplierNameID));
            parameters.put("date1", date1);
            parameters.put("date2", date2);
            
            

            JasperReport jreport = JasperCompileManager.compileReport("D:\\WORK\\DOAN\\HK2\\JAVA\\StoreManagement\\StoreManagement\\StoreManagement\\src\\view\\reportInventure.jrxml");
            JasperPrint jprint = JasperFillManager.fillReport(jreport, parameters, conn);
            JasperViewer.viewReport(jprint,false );

        } catch (JRException e) {
        }catch(SQLException exq){

        }
    
    
    }
    public void PrintReport2(String productID, String productTypeID, String supplierNameID,String date1,String date2)
    {
    
        Connection conn = null;
        try {

            DataAccessHelper.getInstance().getConnect();
            conn = DataAccessHelper.getInstance().conn;
            Map<String,Object> parameters = new HashMap<String,Object>();
            parameters.put("p_id", Integer.parseInt(productID));
            parameters.put("productCate_id", Integer.parseInt(productTypeID));
            parameters.put("supplier_id", Integer.parseInt(supplierNameID));
            parameters.put("date1", date1);
            parameters.put("date2", date2);
            
            

            JasperReport jreport = JasperCompileManager.compileReport("D:\\WORK\\DOAN\\HK2\\JAVA\\StoreManagement\\StoreManagement\\StoreManagement\\src\\view\\reportInventure3.jrxml");
            JasperPrint jprint = JasperFillManager.fillReport(jreport, parameters, conn);
            JasperViewer.viewReport(jprint,false );

        } catch (JRException e) {
        }catch(SQLException exq){

        }
    
    
    }
     public void PrintReportToYear(String productID, String productTypeID, String supplierNameID,String date1,String date2)
    {
    
        Connection conn = null;
        try {

            DataAccessHelper.getInstance().getConnect();
            conn = DataAccessHelper.getInstance().conn;
            Map<String,Object> parameters = new HashMap<String,Object>();
            parameters.put("p_id", Integer.parseInt(productID));
            parameters.put("productCate_id", Integer.parseInt(productTypeID));
            parameters.put("supplier_id", Integer.parseInt(supplierNameID));
            parameters.put("date1", date1);
            parameters.put("date2", date2);
            
            

            JasperReport jreport = JasperCompileManager.compileReport("D:\\WORK\\DOAN\\HK2\\JAVA\\StoreManagement\\StoreManagement\\StoreManagement\\src\\view\\reportInventure2.jrxml");
            JasperPrint jprint = JasperFillManager.fillReport(jreport, parameters, conn);
            JasperViewer.viewReport(jprint,false );

        } catch (JRException e) {
        }catch(SQLException exq){

        }
    
    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FReportInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FReportInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FReportInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FReportInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FReportInventory.getInstance().setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbSupplierAll;
    private javax.swing.JComboBox<String> cbproductAll;
    private javax.swing.JComboBox<String> cbproductCategory;
    private javax.swing.JComboBox<String> cbtypeReport;
    private com.toedter.calendar.JDateChooser datapicker1;
    private com.toedter.calendar.JDateChooser datapicker2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    @Override
    public void reload() {
      reportController.loadProduct(cbproductAll); 
        
        cbproductAll.setSelectedIndex(1);
        
        reportController.loadProductCategory(cbproductCategory);
        cbproductCategory.setSelectedIndex(1);
        reportController.loadSupplier(cbSupplierAll);
        cbSupplierAll.setSelectedIndex(1);
    }

    @Override
    public void releaseAction() {

    }

    @Override
    public void update() {

    }

    @Override
    public void addAction() {

    }
}
